### PR TITLE
Randomized scheduler branch

### PR DESCRIPTION
**Pull request by tgflynn**
This schedules dash to run at different randomly selected times over the hour.

Maybe there should be a new branch for testing this.

### CODE REVIEW

**Comment by ghost** [comment]
utACK

**Comment by taw00** [comment]
Question: Is there a danger that sentinel runs overlap each other? Is that a problem? And if locks are used, can that end up stacking sentinel instances up? Should sentinel really be a singleton per configuration profile?

I randomized sentinel runs just by adding random sleep to my crontab call. Crude, but worked. But I always had to ensure the baseline (non-random) schedule was a larger interval than the random component. Why? Because I didn't know what the behavior was if you ran multiple sentinel instances.

Has the overlapping sentinel instance scenario been vetted?

**Comment by tgflynn** [comment]
The randomized scheduler doesn't cause runs to overlap.  sentinel is still invoked by cron every 1 or 2 minutes but if the time at invocation doesn't match the schedule it simply exits without doing any work.

As far as other cases where more than one sentinel instances attempt to run at the same time there is an existing protection mechanism to prevent that.

In any case it looks like this PR will likely be closed in favor of a different implementation by @nmarley .

**Comment by tgflynn** [comment]
Closing in favor of PR #8.

**Pull request closed without merging**
