### PR TITLE
ensure whitespace disallowed in string fields

### PR DESCRIPTION
**Pull request by nmarley**
* adds check so proposal URI can't have leading/trailing whitespace
* adds tests for string fields for proposals and superblocks

### CODE REVIEW

**Review by UdjinM6 — CHANGES_REQUESTED** [review]
Should not only have no leading/trailing whetespaces in name/url but no whitespaces at all. See https://github.com/dashpay/dash/blob/develop/src/test/data/proposals_invalid.json (some of them would pass in your case).

**Comment by nmarley** [comment]
Ah ok, got it. Have updated to disallow any whitespace in proposal URLs.

**Comment by UdjinM6** [comment]
Looks better :) But why no changes for "name" (see this test https://github.com/dashpay/dash/blob/develop/src/test/data/proposals_invalid.json#L6)?

**Comment by nmarley** [comment]
Proposal name already has a pretty tight regex check which doesn't allow spaces: https://github.com/dashpay/sentinel/blob/4b51cf875b68fd46eb0015eb5800cf6bf11d6ad7/lib/models.py#L296

But I can add this test from Core to ensure no regression.

**Review by UdjinM6 — APPROVED** [review]
Ah, I see! Should be good then 👍 

utACK

**Comment by UdjinM6** [comment]
Should also fix PR title now btw ;)

**Pull request merged**
