### PR TITLE
[SECURITY] Exception handling in sentinel is too coarse-grained

### PR DESCRIPTION
**Pull request by fireice-uk**
Further to our conversation on the forum, @nmarley , let me explain why the previous fix is insufficient

- Consider an exception from an invalid object being thrown somewhere in `import_gobject_from_dashd`
- At this point all processing of the `golist` stops, if you are unlucky, this could happen on the first object and you haven't processed anything.
- Since the exception is caught, execution continues, but sentinel hasn't got a complete picture of the gobject list.
- If the sentinel didn't process a watchdog before the exception was thrown, it will attempt to create one
- This can repeat, stopped only by the rate-limiting in the daemon

In practice this can be abused to trip all masternodes into watchdog expired.

### CODE REVIEW

**Comment by UdjinM6** [comment]
@nmarley any thoughts on this one?

**Comment by nmarley** [comment]
In theory invalid gobjects should be voted down _inside_ the `import_gobject_from_dashd` method here: https://github.com/dashpay/sentinel/blob/master/lib/models.py#L146 ... but it's possible an exception could slip thru the cracks before/after the `try` in that method and the validity checks obviously won't catch that.

I do recall working on a similar fix for the "47,5" issue a couple months ago, but without an example of an invalid object or stacktrace to look at, can't say for sure. Probably won't hurt to add more fine-grained exception handling in any case.

We'll want to test this thoroughly first, ideally with a test which has an invalid gobject in the mocked gobject list, to ensure this catches the Exception and continues. @fireice-uk, would you be able to add a test for this case?

**Comment by fireice-uk** [comment]
@nmarley 
I deliberately avoid using term `invalid` as I am aware that this is a property of a dash object. What I'm talking about is a syntactically incorrect object. Consider the simplest case where a dash object has `f` appended to it. The execution will never get to the line you linked. It will throw here: https://github.com/dashpay/sentinel/blob/f761fc94907e8835a263d34c710f1895a0ba16b4/lib/dashlib.py#L211 because the hex encoding has an odd length, and then proceed directly to the exception handler that I modified.

I will have a look on how to add a test like that.

**Comment by fireice-uk** [comment]
@nmarley 
I only had a 30 minute look, so it is possible that I missed something, but I don't think you have a test on "what should happen if we can't make sense of the object presented to us". 

I can add a case to `test_dashd_data_shims.py` where `SHIM_deserialise_from_dashd` throws, but I don't think it would test much.

Let me know what you think.

**Comment by nmarley** [comment]
> Consider the simplest case where a dash object has f appended to it.

This won't happen unless someone's modified Sentinel/DashCore, as this input comes directly from the output of `gobject list`.

> I don't think you have a test on "what should happen if we can't make sense of the object presented to us".

I think you might have a point here -- it would make sense to catch any errors upon import for each object, and continue if there are. But this leaves a situation where an malformed/invalid gobject on the network would never get down-voted and continue to exist on the network indefinitely.

**Comment by fireice-uk** [comment]
> This won't happen unless someone's modified Sentinel/DashCore, as this input comes directly from the output of gobject list.

AFAIK there is nothing stopping someone posting an object like that manually (using DashCore only), or using modified Sentinel. Of course this is only one example - object with invalid json (append `7d` - `}`) would be another case where this is triggered.

> But this leaves a situation where an malformed/invalid gobject on the network would never get down-voted and continue to exist on the network indefinitely.

This can be handled in the exception handler - you can still try to salvage the object hash, even if the body has invalid syntax.

**Comment by ksamuel** [comment]
It's actually a problem I mentioned in this PR: https://github.com/dashpay/sentinel/pull/32. You don't need somebody to use a  modified version of the sentinel, the original client already enter the `except` block.

You see,`subclass()` may return a `Watchdog` object, which `is_valid()` method expect a `dashd` parameter we don't pass. So it does trigger an exception, that is caught by the very broad `except`.

So it's not just code quality, it can definitely hide a bug.

**Comment by nmarley** [comment]
I've reviewed this further and this does seem like a valid concern -- will allow Sentinel to continue processing other gobjects in the case one is malformed.

Normally I would merge this but you've updated your `master` branch since this PR was made, which would pull in that merge commit also. You can see https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/ for more info on what this does.

At this point, I'm going to rebase your 2 commits (`5356a9d`, `d046d94`) onto the current dashpay `develop` branch, push a feature branch and merge that into develop, as we don't need the extra merge commit in this PR. I'll attribute the commit to you so you will get the "credit" for it.

In the future, it will help if you can create a feature branch and create the PR from that (e.g. the "GOOD SCENARIO" from that linked article), it will help keep PRs smaller and focused.

**Comment by nmarley** [comment]
New PR without extra commit is #36

**Pull request closed without merging**
