### PR TITLE
remove trigger size limit

### PR DESCRIPTION
**Pull request by nmarley**
There's no need for this check any longer. Related: https://github.com/dashpay/dash/pull/2298

### CODE REVIEW

**Comment by UdjinM6** [comment]
utACK

I assume this is going to be rebased after #54 , right?

**Comment by nmarley** [comment]
Yes, but this is based on `pending-network-upgrade` branch, so not even sure if that will be necessary. I won't merge this until #54 is merged.

**Comment by nmarley** [comment]
Rebased onto `develop` now that #54 was merged and force-pushed branch. This is now ready for final approval / merge.

**Review by UdjinM6 — APPROVED** [review]
👍 

utACK

**Comment by nmarley** [comment]
TravisCI is broken. Merging as tests pass locally.

**Pull request merged**
