### PR TITLE
submit new simpler format Trigger objects

### PR DESCRIPTION
**Pull request by nmarley**
* changes serialization format of triggers submitted to the new format, which changed serialized trigger size in a test and uncovered a bug in the size check
* fixes a bug in govobj size limit check in superblock creation (use a temp list to check payments, and only add a proposal to the confirmed payments list _after_ size is checked)
* removes remaining `SHIM_serialise_for_dashd` method (not used any longer)

### CODE REVIEW

**Comment by nmarley** [comment]
This is dependent on https://github.com/dashpay/dash/pull/1902 being merged first.

**Comment by UdjinM6** [comment]
Concept ACK but just want to make sure before approving the merge - this actually breaks backwards compatibility, so it can't be rolled out on mainnet until all (or at least majority) MNs upgrade to the new dashd version which would recognize triggers in this new format (i.e. some version with https://github.com/dashpay/dash/pull/1902 applied), right?

**Comment by nmarley** [comment]
Yes, this change should be released _after_ the next Core release, so that we have a transition period for the network where both formats are recognized.

Should we start another branch for future changes that shouldn't go into the next release?

**Comment by UdjinM6** [comment]
Well, this depends on what our plans for sentinel releases are I guess. If we are not going to release the new sentinel version together/before the next Core release then it's good to merge imo. And if that's not the case, then, I agree, we need a new branch for non-compatible features. Or we can just leave such non-compatible PRs without merging till later. I'm fine with either way but they (the branch and/or PRs) will probably require merging/rebasing from time to time to be in sync with `develop`.

**Comment by nmarley** [comment]
> If we are not going to release the new sentinel version together/before the next Core release then it's good to merge imo

Well, I think we have to release it along with the new Core, otherwise the old (current) Sentinel won't recognize the new format and would vote down proposals that Core would let thru.

Probably easier to create another branch for these pending changes. Rebasing is expected, shouldn't be a problem.

**Comment by nmarley** [comment]
Changed PR base branch and resolved conflicts with local rebase

**Review by UdjinM6 — APPROVED** [review]
utACK

**Pull request merged**
