### PR TITLE
Allow to specify rpchost in sentinel config

### PR DESCRIPTION
**Pull request by codablock**
This allows to specify rpchost in sentinel.conf

Needed when run inside docker.

### CODE REVIEW

**Comment by nmarley** [comment]
I think we should default this similar to the `rpcport` argument, right (as opposed to the network)?

**Comment by codablock** [comment]
@nmarley The rpchost is the same for all networks, it's always localhost by default. Or did I misunderstand you?

**Comment by nmarley** [comment]
I mean it can be extracted and defaulted just like the `rpcport` is currently, e.g. something like https://github.com/nmarley/sentinel/commit/8f5829c6623d302cf5d27629813fe7b9c036257d

**Comment by codablock** [comment]
Ah now I understand. That's actually how I implemented it in the beginning, but then realized that the rpchost is not specified in dash.conf. The dash.conf only contains the rpcport and rpcbind, but nothing like the hostname.

That's why I decided to not put this configuration value into dash.conf but into sentinel.conf instead.

**Review by nmarley — APPROVED** [review]

**Comment by nmarley** [comment]
Ah, that makes more sense. It's always local to the dashd process, so host depends on bind IP + port.

**Comment by UdjinM6** [comment]
If I get it right `rpchost` here is similar to `-rpcconnect` in `dash-cli`.

**Comment by nmarley** [comment]
In that case, should this be renamed to `rpcconnect` in the `sentinel.conf` file in order to stick w/the convention?

**Comment by UdjinM6** [comment]
I have no preferences: `rpchost` looks a bit more common while `rpcconnect` is what it is in dash-cli (for whatever reason). I'm ok with both :)

**Comment by codablock** [comment]
Wherever I've seen configuration parameters for BTC/Dash RPC hosts, it was always called rpchost, rpc_host, host, ... (for example in multifaucet). dash-cli was the first one I encoutered a different naming. So I'd prefer to stick with rpchost. If you're ok with that, I'll merge after a :+1: :)

**Comment by nmarley** [comment]
LGTM, :shipit:

**Comment by UdjinM6** [comment]
Yep, in Bitcoin/Dash it is most likely a legacy thing which came from `connect`/`port` for p2p by adding `rpc` prefix instead of following common practice...

**Pull request merged**
